### PR TITLE
Update borsh to 0.3.0: bringing fixes from near-api-js

### PR DESCRIPTION
**Pull request by ilblackdragon**

### CODE REVIEW

**Comment by vgrichina** [comment]
@ilblackdragon I think it makes sense to bring in jsfuzz setup + more serialization tests (e.g. our transactions stuff).

**Comment by vgrichina** [comment]
@ilblackdragon jsfuzz was instrumental in finding some bugs (e.g. UTF-8 handling issue).

**Comment by frol** [comment]
What is the state of this PR?

**Comment by volovyk-s** [comment]
This logic is merged with [this](https://github.com/near/borsh/pull/105) PR

**Pull request closed without merging**
